a = "hdnd"
print(len(a))
print(a[0:3:2])
print(a.count("d"))
print(a.find("n"))
print(a.replace("h", "m"))
print(a.endswith("l"))
print(a.capitalize())
print(a.upper())
print(a.startswith("h"))
print(a.isalnum())
print(a.isalpha())
print(a.isnumeric())
print(a.casefold())
print(a.join("ab"))
